version: "3.9"
services:
    binance_l2_book:
        image: cryptostore
        restart: always
        container_name: BINANCE_L2_BOOK
        volumes:
            - /home/furkan/cryptostore:/cryptostore
        environment:
            - EXCHANGE=BINANCE
            - CHANNELS=l2_book
            - SYMBOLS=ETH-BTC,LTC-BTC,BNB-BTC,BTC-USDT,ETH-USDT,LINK-BTC,EOS-BTC,ETC-BTC,TRX-BTC,XRP-BTC,BNB-USDT,MANA-BTC,ADA-BTC,LTC-USDT,ZIL-BTC,ADA-USDT,XRP-USDT,EOS-USDT,TRX-USDT,ETC-USDT,LINK-USDT,ZIL-USDT,MATIC-BTC,MATIC-USDT,ATOM-BTC,ATOM-USDT,FTM-BTC,FTM-USDT,DOGE-BTC,DOGE-USDT,CHZ-BTC,CHZ-USDT,BNB-BUSD,BTC-BUSD,XRP-BUSD,ETH-BUSD,LTC-BUSD,LINK-BUSD,ETC-BUSD,TRX-BUSD,EOS-BUSD,ADA-BUSD,BCH-BTC,BCH-USDT,BCH-BUSD,FTT-BTC,FTT-USDT,ATOM-BUSD,SOL-BTC,SOL-USDT,SOL-BUSD,MATIC-BUSD,ZIL-BUSD,SNX-BTC,SNX-BUSD,SNX-USDT,MKR-BTC,MKR-USDT,MKR-BUSD,MANA-BUSD,DOGE-BUSD,MANA-USDT,CRV-BTC,CRV-BUSD,CRV-USDT,SAND-BTC,SAND-USDT,SAND-BUSD,DOT-BTC,DOT-BUSD,DOT-USDT,WBTC-BTC,UNI-BTC,UNI-BUSD,UNI-USDT,AVAX-BTC,AVAX-BUSD,AVAX-USDT,AAVE-BTC,AAVE-BUSD,AAVE-USDT,NEAR-BTC,NEAR-BUSD,NEAR-USDT,FIL-BTC,FIL-BUSD,FIL-USDT,AXS-BTC,AXS-BUSD,AXS-USDT,GRT-BTC,GRT-USDT,GRT-BUSD,CHZ-BUSD,SHIB-USDT,SHIB-BUSD,FTM-BUSD,FTT-BUSD,FLOW-BTC,FLOW-BUSD,FLOW-USDT,XEC-BUSD,XEC-USDT,GALA-USDT,GALA-BUSD,GALA-BTC,GMT-BTC,GMT-BUSD,GMT-USDT,APE-USDT,APE-BUSD,APE-BTC,LDO-BUSD,LDO-USDT,LDO-BTC,USTC-BUSD,WBTC-BUSD,SNT-BUSD
            - BACKEND=KAFKA
            - HOST='redpanda:29092'
    binance_trades:
        image: cryptostore
        restart: always
        container_name: BINANCE_TRADES
        volumes:
            - /home/furkan/cryptostore:/cryptostore
        environment:
            - EXCHANGE=BINANCE
            - CHANNELS=trades
            - SYMBOLS=ETH-BTC,LTC-BTC,BNB-BTC,BTC-USDT,ETH-USDT,LINK-BTC,EOS-BTC,ETC-BTC,TRX-BTC,XRP-BTC,BNB-USDT,MANA-BTC,ADA-BTC,LTC-USDT,ZIL-BTC,ADA-USDT,XRP-USDT,EOS-USDT,TRX-USDT,ETC-USDT,LINK-USDT,ZIL-USDT,MATIC-BTC,MATIC-USDT,ATOM-BTC,ATOM-USDT,FTM-BTC,FTM-USDT,DOGE-BTC,DOGE-USDT,CHZ-BTC,CHZ-USDT,BNB-BUSD,BTC-BUSD,XRP-BUSD,ETH-BUSD,LTC-BUSD,LINK-BUSD,ETC-BUSD,TRX-BUSD,EOS-BUSD,ADA-BUSD,BCH-BTC,BCH-USDT,BCH-BUSD,FTT-BTC,FTT-USDT,ATOM-BUSD,SOL-BTC,SOL-USDT,SOL-BUSD,MATIC-BUSD,ZIL-BUSD,SNX-BTC,SNX-BUSD,SNX-USDT,MKR-BTC,MKR-USDT,MKR-BUSD,MANA-BUSD,DOGE-BUSD,MANA-USDT,CRV-BTC,CRV-BUSD,CRV-USDT,SAND-BTC,SAND-USDT,SAND-BUSD,DOT-BTC,DOT-BUSD,DOT-USDT,WBTC-BTC,UNI-BTC,UNI-BUSD,UNI-USDT,AVAX-BTC,AVAX-BUSD,AVAX-USDT,AAVE-BTC,AAVE-BUSD,AAVE-USDT,NEAR-BTC,NEAR-BUSD,NEAR-USDT,FIL-BTC,FIL-BUSD,FIL-USDT,AXS-BTC,AXS-BUSD,AXS-USDT,GRT-BTC,GRT-USDT,GRT-BUSD,CHZ-BUSD,SHIB-USDT,SHIB-BUSD,FTM-BUSD,FTT-BUSD,FLOW-BTC,FLOW-BUSD,FLOW-USDT,XEC-BUSD,XEC-USDT,GALA-USDT,GALA-BUSD,GALA-BTC,GMT-BTC,GMT-BUSD,GMT-USDT,APE-USDT,APE-BUSD,APE-BTC,LDO-BUSD,LDO-USDT,LDO-BTC,USTC-BUSD,WBTC-BUSD,SNT-BUSD
            - BACKEND=KAFKA
            - HOST='redpanda:29092'
    binance_ticker:
        image: cryptostore
        restart: always
        container_name: BINANCE_TICKER
        volumes:
            - /home/furkan/cryptostore:/cryptostore
        environment:
            - EXCHANGE=BINANCE
            - CHANNELS=ticker
            - SYMBOLS=ETH-BTC,LTC-BTC,BNB-BTC,BTC-USDT,ETH-USDT,LINK-BTC,EOS-BTC,ETC-BTC,TRX-BTC,XRP-BTC,BNB-USDT,MANA-BTC,ADA-BTC,LTC-USDT,ZIL-BTC,ADA-USDT,XRP-USDT,EOS-USDT,TRX-USDT,ETC-USDT,LINK-USDT,ZIL-USDT,MATIC-BTC,MATIC-USDT,ATOM-BTC,ATOM-USDT,FTM-BTC,FTM-USDT,DOGE-BTC,DOGE-USDT,CHZ-BTC,CHZ-USDT,BNB-BUSD,BTC-BUSD,XRP-BUSD,ETH-BUSD,LTC-BUSD,LINK-BUSD,ETC-BUSD,TRX-BUSD,EOS-BUSD,ADA-BUSD,BCH-BTC,BCH-USDT,BCH-BUSD,FTT-BTC,FTT-USDT,ATOM-BUSD,SOL-BTC,SOL-USDT,SOL-BUSD,MATIC-BUSD,ZIL-BUSD,SNX-BTC,SNX-BUSD,SNX-USDT,MKR-BTC,MKR-USDT,MKR-BUSD,MANA-BUSD,DOGE-BUSD,MANA-USDT,CRV-BTC,CRV-BUSD,CRV-USDT,SAND-BTC,SAND-USDT,SAND-BUSD,DOT-BTC,DOT-BUSD,DOT-USDT,WBTC-BTC,UNI-BTC,UNI-BUSD,UNI-USDT,AVAX-BTC,AVAX-BUSD,AVAX-USDT,AAVE-BTC,AAVE-BUSD,AAVE-USDT,NEAR-BTC,NEAR-BUSD,NEAR-USDT,FIL-BTC,FIL-BUSD,FIL-USDT,AXS-BTC,AXS-BUSD,AXS-USDT,GRT-BTC,GRT-USDT,GRT-BUSD,CHZ-BUSD,SHIB-USDT,SHIB-BUSD,FTM-BUSD,FTT-BUSD,FLOW-BTC,FLOW-BUSD,FLOW-USDT,XEC-BUSD,XEC-USDT,GALA-USDT,GALA-BUSD,GALA-BTC,GMT-BTC,GMT-BUSD,GMT-USDT,APE-USDT,APE-BUSD,APE-BTC,LDO-BUSD,LDO-USDT,LDO-BTC,USTC-BUSD,WBTC-BUSD,SNT-BUSD
            - BACKEND=KAFKA
            - HOST='redpanda:29092'
    binance_candles:
        image: cryptostore
        restart: always
        container_name: BINANCE_CANDLES
        volumes:
            - /home/furkan/cryptostore:/cryptostore
        environment:
            - EXCHANGE=BINANCE
            - CHANNELS=candles
            - SYMBOLS=ETH-BTC,LTC-BTC,BNB-BTC,BTC-USDT,ETH-USDT,LINK-BTC,EOS-BTC,ETC-BTC,TRX-BTC,XRP-BTC,BNB-USDT,MANA-BTC,ADA-BTC,LTC-USDT,ZIL-BTC,ADA-USDT,XRP-USDT,EOS-USDT,TRX-USDT,ETC-USDT,LINK-USDT,ZIL-USDT,MATIC-BTC,MATIC-USDT,ATOM-BTC,ATOM-USDT,FTM-BTC,FTM-USDT,DOGE-BTC,DOGE-USDT,CHZ-BTC,CHZ-USDT,BNB-BUSD,BTC-BUSD,XRP-BUSD,ETH-BUSD,LTC-BUSD,LINK-BUSD,ETC-BUSD,TRX-BUSD,EOS-BUSD,ADA-BUSD,BCH-BTC,BCH-USDT,BCH-BUSD,FTT-BTC,FTT-USDT,ATOM-BUSD,SOL-BTC,SOL-USDT,SOL-BUSD,MATIC-BUSD,ZIL-BUSD,SNX-BTC,SNX-BUSD,SNX-USDT,MKR-BTC,MKR-USDT,MKR-BUSD,MANA-BUSD,DOGE-BUSD,MANA-USDT,CRV-BTC,CRV-BUSD,CRV-USDT,SAND-BTC,SAND-USDT,SAND-BUSD,DOT-BTC,DOT-BUSD,DOT-USDT,WBTC-BTC,UNI-BTC,UNI-BUSD,UNI-USDT,AVAX-BTC,AVAX-BUSD,AVAX-USDT,AAVE-BTC,AAVE-BUSD,AAVE-USDT,NEAR-BTC,NEAR-BUSD,NEAR-USDT,FIL-BTC,FIL-BUSD,FIL-USDT,AXS-BTC,AXS-BUSD,AXS-USDT,GRT-BTC,GRT-USDT,GRT-BUSD,CHZ-BUSD,SHIB-USDT,SHIB-BUSD,FTM-BUSD,FTT-BUSD,FLOW-BTC,FLOW-BUSD,FLOW-USDT,XEC-BUSD,XEC-USDT,GALA-USDT,GALA-BUSD,GALA-BTC,GMT-BTC,GMT-BUSD,GMT-USDT,APE-USDT,APE-BUSD,APE-BTC,LDO-BUSD,LDO-USDT,LDO-BTC,USTC-BUSD,WBTC-BUSD,SNT-BUSD
            - BACKEND=KAFKA
            - HOST='redpanda:29092'
    ftx_l2_book:
        image: cryptostore
        restart: always
        container_name: FTX_L2_BOOK
        volumes:
            - /home/furkan/cryptostore:/cryptostore
        environment:
            - EXCHANGE=FTX
            - CHANNELS=l2_book
            - SYMBOLS=AAVE-USD-PERP,AAVE-USD-22Z30,AAVE-USD,AAVE-USDT,ADA-USD-PERP,ADA-USD-22Z30,APE-USD-PERP,APE-USD-22Z30,APE-USD,ATOM-USD-PERP,ATOM-USD-22Z30,ATOM-USD,ATOM-USDT,AVAX-USD-PERP,AVAX-USD-22Z30,AVAX-BTC,AVAX-USD,AVAX-USDT,AXS-USD-PERP,AXS-USD-22Z30,AXS-USD,BCH-USD-PERP,BCH-USD-22Z30,BCH-BTC,BCH-USD,BCH-USDT,BNB-USD-PERP,BNB-USD-22Z30,BNB-BTC,BNB-USD,BNB-USDT,BTC-USD-PERP,BTC-USD-22Z30,BTC-USD-22H31,BTC-USD,BTC-USDT,CHZ-USD-PERP,CHZ-USD-22Z30,CHZ-USD,CHZ-USDT,CRV-USD-PERP,CRV-USD,DAI-USD,DAI-USDT,DOGE-USD-PERP,DOGE-USD-22Z30,DOGE-BTC,DOGE-USD,DOGE-USDT,DOT-USD-PERP,DOT-USD-22Z30,DOT-BTC,DOT-USD,DOT-USDT,EOS-USD-PERP,EOS-USD-22Z30,ETC-USD-PERP,ETH-USD-PERP,ETH-USD-22Z30,ETH-USD-22H31,ETH-BTC,ETH-USD,ETH-USDT,FIL-USD-PERP,FIL-USD-22Z30,FLOW-USD-PERP,FTM-USD-PERP,FTM-USD-22Z30,FTM-USD,FTT-USD-PERP,FTT-BTC,FTT-USD,FTT-USDT,GALA-USD-PERP,GALA-USD,GMT-USD-PERP,GMT-USD-22Z30,GMT-USD,GRT-USD-PERP,GRT-USD-22Z30,GRT-USD,LDO-USD-PERP,LDO-USD,LINK-USD-PERP,LINK-USD-22Z30,LINK-BTC,LINK-USD,LINK-USDT,LTC-USD-PERP,LTC-USD-22Z30,LTC-BTC,LTC-USD,LTC-USDT,MANA-USD-PERP,MANA-USD,MATIC-USD-PERP,MATIC-USD-22Z30,MATIC-BTC,MATIC-USD,MKR-USD-PERP,MKR-USD,MKR-USDT,NEAR-USD-PERP,NEAR-USD-22Z30,NEAR-USD,NEAR-USDT,SAND-USD-PERP,SAND-USD,SHIB-USD-PERP,SHIB-USD,SNX-USD-PERP,SNX-USD,SOL-USD-PERP,SOL-USD-22Z30,SOL-BTC,SOL-USD,SOL-USDT,TRX-USD-PERP,TRX-USD-22Z30,TRX-BTC,TRX-USD,TRX-USDT,UNI-USD-PERP,UNI-USD-22Z30,UNI-BTC,UNI-USD,UNI-USDT,USTC-USD-PERP,WBTC-BTC,WBTC-USD,XRP-USD-PERP,XRP-USD-22Z30,XRP-BTC,XRP-USD,XRP-USDT,ZIL-USD-PERP,ZECBULL-USD
            - BACKEND=KAFKA
            - HOST='redpanda:29092'
    ftx_trades:
        image: cryptostore
        restart: always
        container_name: FTX_TRADES
        volumes:
            - /home/furkan/cryptostore:/cryptostore
        environment:
            - EXCHANGE=FTX
            - CHANNELS=trades
            - SYMBOLS=AAVE-USD-PERP,AAVE-USD-22Z30,AAVE-USD,AAVE-USDT,ADA-USD-PERP,ADA-USD-22Z30,APE-USD-PERP,APE-USD-22Z30,APE-USD,ATOM-USD-PERP,ATOM-USD-22Z30,ATOM-USD,ATOM-USDT,AVAX-USD-PERP,AVAX-USD-22Z30,AVAX-BTC,AVAX-USD,AVAX-USDT,AXS-USD-PERP,AXS-USD-22Z30,AXS-USD,BCH-USD-PERP,BCH-USD-22Z30,BCH-BTC,BCH-USD,BCH-USDT,BNB-USD-PERP,BNB-USD-22Z30,BNB-BTC,BNB-USD,BNB-USDT,BTC-USD-PERP,BTC-USD-22Z30,BTC-USD-22H31,BTC-USD,BTC-USDT,CHZ-USD-PERP,CHZ-USD-22Z30,CHZ-USD,CHZ-USDT,CRV-USD-PERP,CRV-USD,DAI-USD,DAI-USDT,DOGE-USD-PERP,DOGE-USD-22Z30,DOGE-BTC,DOGE-USD,DOGE-USDT,DOT-USD-PERP,DOT-USD-22Z30,DOT-BTC,DOT-USD,DOT-USDT,EOS-USD-PERP,EOS-USD-22Z30,ETC-USD-PERP,ETH-USD-PERP,ETH-USD-22Z30,ETH-USD-22H31,ETH-BTC,ETH-USD,ETH-USDT,FIL-USD-PERP,FIL-USD-22Z30,FLOW-USD-PERP,FTM-USD-PERP,FTM-USD-22Z30,FTM-USD,FTT-USD-PERP,FTT-BTC,FTT-USD,FTT-USDT,GALA-USD-PERP,GALA-USD,GMT-USD-PERP,GMT-USD-22Z30,GMT-USD,GRT-USD-PERP,GRT-USD-22Z30,GRT-USD,LDO-USD-PERP,LDO-USD,LINK-USD-PERP,LINK-USD-22Z30,LINK-BTC,LINK-USD,LINK-USDT,LTC-USD-PERP,LTC-USD-22Z30,LTC-BTC,LTC-USD,LTC-USDT,MANA-USD-PERP,MANA-USD,MATIC-USD-PERP,MATIC-USD-22Z30,MATIC-BTC,MATIC-USD,MKR-USD-PERP,MKR-USD,MKR-USDT,NEAR-USD-PERP,NEAR-USD-22Z30,NEAR-USD,NEAR-USDT,SAND-USD-PERP,SAND-USD,SHIB-USD-PERP,SHIB-USD,SNX-USD-PERP,SNX-USD,SOL-USD-PERP,SOL-USD-22Z30,SOL-BTC,SOL-USD,SOL-USDT,TRX-USD-PERP,TRX-USD-22Z30,TRX-BTC,TRX-USD,TRX-USDT,UNI-USD-PERP,UNI-USD-22Z30,UNI-BTC,UNI-USD,UNI-USDT,USTC-USD-PERP,WBTC-BTC,WBTC-USD,XRP-USD-PERP,XRP-USD-22Z30,XRP-BTC,XRP-USD,XRP-USDT,ZIL-USD-PERP,ZECBULL-USD
            - BACKEND=KAFKA
            - HOST='redpanda:29092'
    ftx_ticker:
        image: cryptostore
        restart: always
        container_name: FTX_TICKER
        volumes:
            - /home/furkan/cryptostore:/cryptostore
        environment:
            - EXCHANGE=FTX
            - CHANNELS=ticker
            - SYMBOLS=AAVE-USD-PERP,AAVE-USD-22Z30,AAVE-USD,AAVE-USDT,ADA-USD-PERP,ADA-USD-22Z30,APE-USD-PERP,APE-USD-22Z30,APE-USD,ATOM-USD-PERP,ATOM-USD-22Z30,ATOM-USD,ATOM-USDT,AVAX-USD-PERP,AVAX-USD-22Z30,AVAX-BTC,AVAX-USD,AVAX-USDT,AXS-USD-PERP,AXS-USD-22Z30,AXS-USD,BCH-USD-PERP,BCH-USD-22Z30,BCH-BTC,BCH-USD,BCH-USDT,BNB-USD-PERP,BNB-USD-22Z30,BNB-BTC,BNB-USD,BNB-USDT,BTC-USD-PERP,BTC-USD-22Z30,BTC-USD-22H31,BTC-USD,BTC-USDT,CHZ-USD-PERP,CHZ-USD-22Z30,CHZ-USD,CHZ-USDT,CRV-USD-PERP,CRV-USD,DAI-USD,DAI-USDT,DOGE-USD-PERP,DOGE-USD-22Z30,DOGE-BTC,DOGE-USD,DOGE-USDT,DOT-USD-PERP,DOT-USD-22Z30,DOT-BTC,DOT-USD,DOT-USDT,EOS-USD-PERP,EOS-USD-22Z30,ETC-USD-PERP,ETH-USD-PERP,ETH-USD-22Z30,ETH-USD-22H31,ETH-BTC,ETH-USD,ETH-USDT,FIL-USD-PERP,FIL-USD-22Z30,FLOW-USD-PERP,FTM-USD-PERP,FTM-USD-22Z30,FTM-USD,FTT-USD-PERP,FTT-BTC,FTT-USD,FTT-USDT,GALA-USD-PERP,GALA-USD,GMT-USD-PERP,GMT-USD-22Z30,GMT-USD,GRT-USD-PERP,GRT-USD-22Z30,GRT-USD,LDO-USD-PERP,LDO-USD,LINK-USD-PERP,LINK-USD-22Z30,LINK-BTC,LINK-USD,LINK-USDT,LTC-USD-PERP,LTC-USD-22Z30,LTC-BTC,LTC-USD,LTC-USDT,MANA-USD-PERP,MANA-USD,MATIC-USD-PERP,MATIC-USD-22Z30,MATIC-BTC,MATIC-USD,MKR-USD-PERP,MKR-USD,MKR-USDT,NEAR-USD-PERP,NEAR-USD-22Z30,NEAR-USD,NEAR-USDT,SAND-USD-PERP,SAND-USD,SHIB-USD-PERP,SHIB-USD,SNX-USD-PERP,SNX-USD,SOL-USD-PERP,SOL-USD-22Z30,SOL-BTC,SOL-USD,SOL-USDT,TRX-USD-PERP,TRX-USD-22Z30,TRX-BTC,TRX-USD,TRX-USDT,UNI-USD-PERP,UNI-USD-22Z30,UNI-BTC,UNI-USD,UNI-USDT,USTC-USD-PERP,WBTC-BTC,WBTC-USD,XRP-USD-PERP,XRP-USD-22Z30,XRP-BTC,XRP-USD,XRP-USDT,ZIL-USD-PERP,ZECBULL-USD
            - BACKEND=KAFKA
            - HOST='redpanda:29092'
    redpanda:
        command:
            - redpanda
            - start
            - --smp 1
            - --overprovisioned
            - --node-id 0
            - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
            - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
        image: docker.vectorized.io/vectorized/redpanda:v21.11.15
        container_name: redpanda
        hostname: redpanda
        ports:
            - "9092:9092"
            - "29092:29092"
        