exchanges:
  - BINANCE
  - FTX

symbols:
#   COINBASE: [BTC,ETH,BNB,XRP,ADA,SOL,DOGE,DOT,MATIC,DAI,SHIB,TRX,AVAX,WBTC,UNI,ETC,LTC,FTT,ATOM,NEAR,LINK,XMR,XLM,BCH,FLOW,ALGO,VET,ICP,FIL,APE,MANA,SAND,EOS,XTZ,HBAR,CHZ,EGLD,AAVE,THETA,AXS,QNT,BSV,XEC,ZEC,BTT,MKR,SNX,GRT,KLAY,FTM]
  BINANCE: [BTC,ETH,BNB,XRP,ADA,SOL,DOGE,DOT,MATIC,DAI,SHIB,TRX,AVAX,WBTC,UNI,ETC,LTC,FTT,ATOM,NEAR,LINK,BCH,FLOW,FIL,APE,MANA,SAND,EOS,CHZ,AAVE,AXS,XEC,MKR,SNX,GRT,FTM,LDO,CRV,ZIL,GMT,USTC,GALA]
  FTX: [BTC,ETH,BNB,XRP,ADA,SOL,DOGE,DOT,MATIC,DAI,SHIB,TRX,AVAX,WBTC,UNI,ETC,LTC,FTT,ATOM,NEAR,LINK,BCH,FLOW,FIL,APE,MANA,SAND,EOS,CHZ,AAVE,AXS,XEC,MKR,SNX,GRT,FTM,LDO,CRV,ZIL,GMT,USTC,GALA]
  KRAKEN: [BTC,ETH,BNB,XRP,ADA,SOL,DOGE,DOT,MATIC,DAI,SHIB,TRX,AVAX,WBTC,UNI,ETC,LTC,FTT,ATOM,NEAR,LINK,XMR,XLM,BCH,FLOW,ALGO,VET,ICP,FIL,APE,MANA,SAND,EOS,XTZ,HBAR,CHZ,EGLD,AAVE,THETA,AXS,QNT,BSV,XEC,ZEC,BTT,MKR,SNX,GRT,KLAY,FTM]

channels:
  - l2_book
  - trades
  - ticker
  - candles

symbols_per_channel: 1000

backend: KAFKA
host: redpanda:29092