exchanges:
  - BINANCE
  - BINANCE_FUTURES
  - COINBASE
  - KRAKEN

symbols:
  COINBASE: [BTC,ETH,BNB,XRP,ADA,SOL,DOGE,DOT,MATIC,DAI,SHIB,TRX,AVAX,UNI,ETC,LTC,FTT,ATOM,NEAR,LINK,XMR,XLM,BCH,FLOW,ALGO,VET,ICP,FIL,APE,MANA,SAND,EOS,XTZ,HBAR,CHZ,EGLD,AAVE,THETA,AXS,QNT,BSV,XEC,ZEC,BTT,MKR,SNX,GRT,KLAY,FTM]
  BINANCE: [BTC,ETH,BNB,XRP,ADA,SOL,DOGE,DOT,MATIC,DAI,SHIB,TRX,AVAX,WBTC,UNI,ETC,LTC,FTT,ATOM,NEAR,LINK,BCH,FLOW,FIL,APE,MANA,SAND,EOS,CHZ,AAVE,AXS,XEC,MKR,SNX,GRT,FTM,LDO,CRV,ZIL,GMT,USTC,GALA]
  BINANCE_FUTURES: [BTC,ETH,BNB,XRP,ADA,SOL,DOGE,DOT,MATIC,DAI,SHIB,TRX,AVAX,WBTC,UNI,ETC,LTC,FTT,ATOM,NEAR,LINK,BCH,FLOW,FIL,APE,MANA,SAND,EOS,CHZ,AAVE,AXS,XEC,MKR,SNX,GRT,FTM,LDO,CRV,ZIL,GMT,USTC,GALA]
  KRAKEN: [BTC,ETH,BNB,XRP,ADA,SOL,DOGE,DOT,MATIC,DAI,SHIB,TRX,AVAX,WBTC,UNI,ETC,LTC,FTT,ATOM,NEAR,LINK,XMR,XLM,BCH,FLOW,ALGO,VET,ICP,FIL,APE,MANA,SAND,EOS,XTZ,HBAR,CHZ,EGLD,AAVE,THETA,AXS,QNT,BSV,XEC,ZEC,BTT,MKR,SNX,GRT,KLAY,FTM]

channels:
  - l2_book
  - trades
  - ticker
  - candles

symbols_per_channel: 1000
depth: 500

backend: QUEST
host: 100.100.105.127
