exchanges:
  - BINANCE
  - BINANCE_FUTURES
  - COINBASE
  - KRAKEN

symbols:
  COINBASE: [BTC,ETH,BNB,XRP,ADA,SOL,DOGE,DOT,MATIC,SHIB,TRX,AVAX,UNI,ETC,LTC,FTT,LINK,XMR,XLM,BCH]
  BINANCE: [BTC,ETH,BNB,XRP,ADA,SOL,DOGE,DOT,MATIC,SHIB,TRX,AVAX,WBTC,UNI,ETC,LTC,FTT,LINK,BCH]
  BINANCE_FUTURES: [BTC,ETH,BNB,XRP,ADA,SOL,DOGE,DOT,MATIC,SHIB,TRX,AVAX,WBTC,UNI,ETC,LTC,FTT,LINK,BCH]
  KRAKEN: [BTC,ETH,BNB,XRP,ADA,SOL,DOGE,DOT,MATIC,SHIB,TRX,AVAX,WBTC,UNI,ETC,LTC,FTT,LINK,XMR,XLM,BCH]

channels:
  - l2_book
  - trades
  - ticker
  - candles

symbols_per_channel: 1000
depth: 100

backend: KAFKA
host: redpanda
port: 19092
