version: "3.9"
services:
    binance:
        image: cryptostore
        restart: always
        container_name: BINANCE
        volumes:
            - /home/furkan/cryptostore:/cryptostore
        environment:
            - EXCHANGE=BINANCE
            - CHANNELS=l2_book,trades,ticker,candles
            - SYMBOLS=ETH-BTC,LTC-BTC,BNB-BTC,BTC-USDT,ETH-USDT,LINK-BTC,EOS-BTC,ETC-BTC,TRX-BTC,XRP-BTC,BNB-USDT,MANA-BTC,ADA-BTC,LTC-USDT,ZIL-BTC,ADA-USDT,XRP-USDT,EOS-USDT,TRX-USDT,ETC-USDT,LINK-USDT,ZIL-USDT,MATIC-BTC,MATIC-USDT,ATOM-BTC,ATOM-USDT,FTM-BTC,FTM-USDT,DOGE-BTC,DOGE-USDT,CHZ-BTC,CHZ-USDT,BNB-BUSD,BTC-BUSD,XRP-BUSD,ETH-BUSD,LTC-BUSD,LINK-BUSD,ETC-BUSD,TRX-BUSD,EOS-BUSD,ADA-BUSD,BCH-BTC,BCH-USDT,BCH-BUSD,ATOM-BUSD,SOL-BTC,SOL-USDT,SOL-BUSD,MATIC-BUSD,ZIL-BUSD,SNX-BTC,SNX-BUSD,SNX-USDT,MKR-BTC,MKR-USDT,MKR-BUSD,MANA-BUSD,DOGE-BUSD,MANA-USDT,CRV-BTC,CRV-BUSD,CRV-USDT,SAND-BTC,SAND-USDT,SAND-BUSD,DOT-BTC,DOT-BUSD,DOT-USDT,WBTC-BTC,UNI-BTC,UNI-BUSD,UNI-USDT,AVAX-BTC,AVAX-BUSD,AVAX-USDT,AAVE-BTC,AAVE-BUSD,AAVE-USDT,NEAR-BTC,NEAR-BUSD,NEAR-USDT,FIL-BTC,FIL-BUSD,FIL-USDT,AXS-BTC,AXS-BUSD,AXS-USDT,GRT-BTC,GRT-USDT,GRT-BUSD,CHZ-BUSD,SHIB-USDT,SHIB-BUSD,FTM-BUSD,FTT-BUSD,FLOW-BTC,FLOW-BUSD,FLOW-USDT,XEC-BUSD,XEC-USDT,GALA-USDT,GALA-BUSD,GALA-BTC,GMT-BTC,GMT-BUSD,GMT-USDT,APE-USDT,APE-BUSD,APE-BTC,LDO-BUSD,LDO-USDT,LDO-BTC,USTC-BUSD,WBTC-BUSD,HOOK-BNB
            - BACKEND=KAFKA
            - DEPTH=500 
            - HOST=redpanda
    binance_futures:
        image: cryptostore
        restart: always
        container_name: BINANCE_FUTURES
        volumes:
            - /home/furkan/cryptostore:/cryptostore
        environment:
            - EXCHANGE=BINANCE_FUTURES
            - CHANNELS=l2_book,trades,ticker,candles
            - SYMBOLS=BTC-USDT-PERP,ETH-USDT-PERP,BCH-USDT-PERP,XRP-USDT-PERP,EOS-USDT-PERP,LTC-USDT-PERP,TRX-USDT-PERP,ETC-USDT-PERP,LINK-USDT-PERP,ADA-USDT-PERP,BNB-USDT-PERP,ATOM-USDT-PERP,ZIL-USDT-PERP,DOGE-USDT-PERP,MKR-USDT-PERP,SNX-USDT-PERP,DOT-USDT-PERP,CRV-USDT-PERP,SOL-USDT-PERP,UNI-USDT-PERP,AVAX-USDT-PERP,FTM-USDT-PERP,NEAR-USDT-PERP,AAVE-USDT-PERP,FIL-USDT-PERP,MATIC-USDT-PERP,AXS-USDT-PERP,GRT-USDT-PERP,BTC-BUSD-PERP,CHZ-USDT-PERP,SAND-USDT-PERP,MANA-USDT-PERP,ETH-BUSD-PERP,BNB-BUSD-PERP,ADA-BUSD-PERP,XRP-BUSD-PERP,DOGE-BUSD-PERP,SOL-BUSD-PERP,GALA-USDT-PERP,FLOW-USDT-PERP,GMT-USDT-PERP,APE-USDT-PERP,AVAX-BUSD-PERP,NEAR-BUSD-PERP,GMT-BUSD-PERP,APE-BUSD-PERP,FTM-BUSD-PERP,GALA-BUSD-PERP,TRX-BUSD-PERP,DOT-BUSD-PERP,LINK-BUSD-PERP,SAND-BUSD-PERP,LTC-BUSD-PERP,MATIC-BUSD-PERP,FIL-BUSD-PERP,ETC-BUSD-PERP,LDO-BUSD-PERP,UNI-BUSD-PERP,LDO-USDT-PERP,BTC-USDT-22Z30,ETH-USDT-22Z30,BTC-USDT-PINDEX,ETH-USDT-PINDEX,BCH-USDT-PINDEX,XRP-USDT-PINDEX,EOS-USDT-PINDEX,LTC-USDT-PINDEX,TRX-USDT-PINDEX,ETC-USDT-PINDEX,LINK-USDT-PINDEX,ADA-USDT-PINDEX,BNB-USDT-PINDEX,ATOM-USDT-PINDEX,ZIL-USDT-PINDEX,DOGE-USDT-PINDEX,MKR-USDT-PINDEX,SNX-USDT-PINDEX,DOT-USDT-PINDEX,CRV-USDT-PINDEX,SOL-USDT-PINDEX,UNI-USDT-PINDEX,AVAX-USDT-PINDEX,FTM-USDT-PINDEX,NEAR-USDT-PINDEX,AAVE-USDT-PINDEX,FIL-USDT-PINDEX,MATIC-USDT-PINDEX,AXS-USDT-PINDEX,GRT-USDT-PINDEX,BTC-BUSD-PINDEX,CHZ-USDT-PINDEX,SAND-USDT-PINDEX,MANA-USDT-PINDEX,ETH-BUSD-PINDEX,BNB-BUSD-PINDEX,ADA-BUSD-PINDEX,XRP-BUSD-PINDEX,DOGE-BUSD-PINDEX,SOL-BUSD-PINDEX,GALA-USDT-PINDEX,FLOW-USDT-PINDEX,GMT-USDT-PINDEX,APE-USDT-PINDEX,AVAX-BUSD-PINDEX,NEAR-BUSD-PINDEX,GMT-BUSD-PINDEX,APE-BUSD-PINDEX,FTM-BUSD-PINDEX,GALA-BUSD-PINDEX,TRX-BUSD-PINDEX,DOT-BUSD-PINDEX,LINK-BUSD-PINDEX,SAND-BUSD-PINDEX,LTC-BUSD-PINDEX,MATIC-BUSD-PINDEX,FIL-BUSD-PINDEX,ETC-BUSD-PINDEX,LDO-BUSD-PINDEX,UNI-BUSD-PINDEX,LDO-USDT-PINDEX,BLUEBIRD-USDT-PINDEX
            - BACKEND=KAFKA
            - DEPTH=500 
            - HOST=redpanda
    coinbase:
        image: cryptostore
        restart: always
        container_name: COINBASE
        volumes:
            - /home/furkan/cryptostore:/cryptostore
        environment:
            - EXCHANGE=COINBASE
            - CHANNELS=l2_book,trades,ticker,candles
            - SYMBOLS=XRP-USD,SHIB-USD,ICP-BTC,DAI-USD,BTC-USD,ATOM-USD,DOT-USDT,ADA-BTC,ETH-BTC,ETH-USDC,NEAR-USDT,ZEC-BTC,MKR-BTC,QNT-USDT,GRT-USD,SNX-USD,MATIC-USDT,FIL-USD,DOGE-USDT,AAVE-USD,ATOM-USDT,EOS-USD,FLOW-USD,ETH-USD,ETC-USD,SOL-USDT,ADA-USD,XTZ-USD,GRT-BTC,FIL-BTC,DAI-USDC,LINK-BTC,ZEC-USDC,MANA-USD,SHIB-USDT,CHZ-USD,ALGO-USD,AVAX-USD,LINK-USD,QNT-USD,UNI-BTC,ALGO-BTC,DOT-BTC,ADA-USDT,APE-USDT,APE-USD,ETC-BTC,SAND-USDT,BTC-USDT,DOT-USD,DOGE-USD,SAND-USD,ETH-USDT,LTC-BTC,ATOM-BTC,SOL-BTC,XLM-USD,ICP-USDT,HBAR-USD,AAVE-BTC,LTC-USD,ZEC-USD,MANA-USDC,DOGE-BTC,BCH-BTC,XLM-USDT,AXS-USDT,MANA-BTC,SOL-USD,AXS-BTC,SNX-BTC,AXS-USD,ICP-USD,MATIC-USD,CHZ-USDT,HBAR-USDT,AVAX-BTC,UNI-USD,ADA-USDC,EGLD-USD,XRP-BTC,NEAR-USD,EOS-BTC,BTC-USDC,XLM-BTC,AVAX-USDT,BCH-USD,LINK-USDT,MKR-USD,MATIC-BTC,XTZ-BTC,FLOW-USDT,BOBA-USD
            - BACKEND=KAFKA
            - DEPTH=500 
            - HOST=redpanda
    kraken:
        image: cryptostore
        restart: always
        container_name: KRAKEN
        volumes:
            - /home/furkan/cryptostore:/cryptostore
        environment:
            - EXCHANGE=KRAKEN
            - CHANNELS=l2_book,trades,ticker,candles
            - SYMBOLS=AAVE-USD,AAVE-BTC,ADA-USD,ADA-USDT,ADA-BTC,ALGO-USD,ALGO-USDT,ALGO-BTC,APE-USD,APE-USDT,ATOM-USD,ATOM-USDT,ATOM-BTC,AVAX-USD,AVAX-USDT,AXS-USD,BCH-USD,BCH-USDT,BCH-BTC,BTT-USD,CHZ-USD,DAI-USD,DAI-USDT,DOT-USD,DOT-USDT,DOT-BTC,EGLD-USD,EOS-USD,EOS-USDT,EOS-BTC,ETH-USDC,ETH-USDT,FIL-USD,FIL-BTC,FLOW-USD,FLOW-BTC,FTM-USD,GRT-USD,GRT-BTC,ICP-USD,LINK-USD,LINK-USDT,LINK-BTC,LTC-USDT,MANA-USD,MANA-USDT,MANA-BTC,MATIC-USD,MATIC-USDT,MATIC-BTC,MKR-USD,MKR-BTC,NEAR-USD,QNT-USD,SAND-USD,SAND-BTC,SHIB-USD,SHIB-USDT,SNX-USD,SNX-BTC,SOL-USD,SOL-USDT,SOL-BTC,TRX-USD,TRX-BTC,UNI-USD,UNI-BTC,WBTC-USD,WBTC-BTC,BTC-USDC,BTC-USDT,DOGE-USD,DOGE-USDT,ETC-BTC,ETC-USD,ETH-BTC,ETH-USD,LTC-BTC,LTC-USD,XMR-USDT,XRP-USDT,XTZ-USD,XTZ-USDT,XTZ-BTC,BTC-USD,DOGE-BTC,XLM-BTC,XLM-USD,XMR-BTC,XMR-USD,XRP-BTC,XRP-USD,ZEC-BTC,ZEC-USD,USD-JPY
            - BACKEND=KAFKA
            - DEPTH=500 
            - HOST=redpanda
        
    redpanda:
        command:
            - redpanda
            - start
            - --smp 1
            - --overprovisioned
            - --node-id 0
            - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
            - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
        image: docker.vectorized.io/vectorized/redpanda:v21.11.15
        container_name: redpanda
        hostname: redpanda
        ports:
            - "9092:9092"
            - "29092:29092"
        